### ISSUE TITLE
Asking about the variable

### ISSUE THREAD

**Issue by CHienSF** [DikshantDulal/SoftServe_QLSTM#1]
Hi DikshantDulal

Good day to you.

Just want to confirm with you for the parameters below:
1. number of layers => number of variational layer (refer to the dash box) i.e., n_qlayers?
2.  What is the n_vrotations refer to? Can't see it be used in the factory.py

Thanks

**Comment by DikshantDulal** [comment]
Hi @CHienSF , 

If you look at the line 141 in Factory.py, the trainable weight shapes is defined as         

`weight_shapes = {"weights": (self.n_qlayers, self.n_vrotations, self.n_qubits)}
`
The value of n_vrotations determines how many rotations gates are applied in each quantum circuit in each layer of the quantum LSTM. Let me know if you have any other questions
